# German translations for all 76 quiz answer options (index-aligned with options[])

OPTIONS_DE = {
    1: [
        "Quell-IP-Adresse",
        "Ziel-IP-Adresse",
        "Quell-Datenverbindungsadresse",
        "Ziel-Datenverbindungsadresse",
    ],
    2: [
        "Das Paket wird zuerst an das Standard-Gateway gesendet und je nach Antwort des Gateways eventuell an den Ziel-Host.",
        "Das Paket wird direkt an den Ziel-Host gesendet.",
        "Das Paket wird zuerst an das Standard-Gateway gesendet und von dort direkt an den Ziel-Host.",
        "Das Paket wird nur an das Standard-Gateway gesendet.",
    ],
    3: [
        "Das Paket über die Gigabit-0/1-Schnittstelle weiterleiten",
        "Einen neuen Layer-2-Ethernet-Frame für das Ziel erstellen",
        "Den ARP-Cache prüfen, um die Ziel-IP-Adresse zu ermitteln",
        "Die Routing-Tabelle prüfen, ob das Zielnetzwerk in der Routing-Tabelle ist",
    ],
    4: ["126.0.0.1", "127.0.0.0", "126.0.0.0", "127.0.0.1"],
    5: [
        "Das Kabel ist nicht richtig an die NIC angeschlossen.",
        "Der Computer hat eine ungültige IP-Adresse.",
        "Der Computer hat eine falsche Subnetzmaske.",
        "Der Computer hat eine ungültige Standard-Gateway-Adresse.",
    ],
    6: [
        "Die IP-Kapselung wird je nach Netzwerkmedium angepasst.",
        "IP verlässt sich auf Layer-2-Protokolle zur Übertragungsfehlerkontrolle.",
        "MAC-Adressen werden bei der IP-Paket-Kapselung verwendet.",
        "IP verlässt sich auf höhere Schichten bei fehlenden oder falsch sortierten Paketen.",
    ],
    7: [
        "Da IPv6 integrierte Sicherheit hat, müssen IPv6-Adressen interner Netze nicht verborgen werden.",
        "Jeder Host kann eine öffentliche IPv6-Adresse erhalten, weil extrem viele IPv6-Adressen verfügbar sind.",
        "NAT-Probleme werden gelöst, weil der IPv6-Header die Paketverarbeitung durch Router verbessert.",
        "End-to-End-Probleme durch NAT werden gelöst, weil die Routenanzahl mit der Anzahl der Internet-Knoten steigt.",
    ],
    8: [
        "der niedrigere Metrikwert des Zielnetzwerks",
        "die niedrigere Gateway-IP-Adresse zum Zielnetzwerk",
        "der höhere Metrikwert des Zielnetzwerks",
        "die höhere Gateway-IP-Adresse zum Zielnetzwerk",
    ],
    9: [
        "Fehlererkennung durchführen",
        "Pakete zum Ziel weiterleiten",
        "PDUs der Transportschicht kapseln",
        "Frames auf das Medium platzieren",
        "Kollisionserkennung",
    ],
    10: [
        "Hosts am Switch können die Standard-Gateway-Adresse des Switches nutzen, um Pakete an ein entferntes Ziel zu senden.",
        "Ein Switch benötigt ein Standard-Gateway, um per Telnet und SSH erreichbar zu sein.",
        "Die Standard-Gateway-Adresse wird genutzt, um vom Switch ausgehende Pakete an entfernte Netze weiterzuleiten.",
        "Sie liefert eine Next-Hop-Adresse für den gesamten durch den Switch fließenden Verkehr.",
    ],
    11: [
        "verbindungslos",
        "medienabhängig",
        "Segmentierung von Nutzerdaten",
        "zuverlässige End-to-End-Übertragung",
    ],
    12: ["Time-to-Live", "Sequenznummer", "Bestätigungsnummer", "Differentiated Services"],
    13: [
        "kleinerer Header",
        "geringerer Aufwand für Prüfsummenberechnung",
        "kleinere Quell- und Ziel-IP-Adressen",
        "effiziente Paketverarbeitung",
    ],
    14: ["Protokoll", "Identifikation", "Version", "Differentiated Services"],
    15: [
        "Pakete mit Ziel 172.17.6.15 → FastEthernet0/0",
        "Pakete mit Ziel 172.17.14.8 → FastEthernet0/1",
        "Pakete mit Ziel 172.17.12.10 → FastEthernet1/0",
        "Pakete mit Ziel 172.17.10.5 → FastEthernet1/1",
        "Pakete mit Ziel 172.17.8.20 → Serial0/0/0",
    ],
    16: [
        "Der TCP/IP-Stack auf dem Gerät funktioniert korrekt.",
        "Das Gerät hat End-to-End-Konnektivität.",
        "DHCP funktioniert korrekt.",
        "Das Ethernet-Kabel funktioniert korrekt.",
        "Das Gerät hat die richtige IP-Adresse im Netzwerk.",
    ],
    17: [
        "direkt verbundene Routen",
        "lokale Routen",
        "Remote-Routen",
        "C- und L-Quellrouten",
    ],
    18: [
        "Sie führen eine eigene lokale Routing-Tabelle mit Route zur Loopback-Schnittstelle, lokaler Netzwerk-Route und Remote-Default-Route.",
        "Sie leiten alle Pakete immer an das Standard-Gateway weiter, das für die Zustellung zuständig ist.",
        "Sie suchen in der lokalen Routing-Tabelle nach einer Route zum Ziel und übergeben diese Information an das Standard-Gateway.",
        "Sie senden ein Abfragepaket an das Standard-Gateway und fragen nach der besten Route.",
    ],
    19: ["Next Header", "Flow Label", "Traffic Class", "Differentiated Services"],
    20: [
        "ARP wird genutzt, um die IP-Adresse eines Hosts in einem anderen Netzwerk zu ermitteln.",
        "ARP wird genutzt, um die IP-Adresse eines Hosts im lokalen Netzwerk zu ermitteln.",
        "ARP wird genutzt, um die MAC-Adresse eines Hosts in einem anderen Netzwerk zu ermitteln.",
        "ARP wird genutzt, um die MAC-Adresse eines Hosts im lokalen Netzwerk zu ermitteln.",
    ],
    21: [
        "Der Frame hat die Broadcast-Adresse als Zieladresse.",
        "Die Zieladresse ist dem Switch unbekannt.",
        "Die Quelladresse im Frame-Header ist die Broadcast-Adresse.",
        "Die Quelladresse im Frame ist eine Multicast-Adresse.",
        "Die Zieladresse im Frame ist eine bekannte Unicast-Adresse.",
    ],
    22: [
        "Sie müssen von allen Routern im lokalen Netzwerk weitergeleitet werden.",
        "Sie werden von jedem Gerät im lokalen Netzwerk empfangen und verarbeitet.",
        "Sie werden von allen Switches im lokalen Netzwerk verworfen.",
        "Sie werden nur vom Zielgerät empfangen und verarbeitet.",
    ],
    23: [
        "0.0.0.0",
        "255.255.255.255",
        "FFFF.FFFF.FFFF",
        "AAAA.AAAA.AAAA",
        "die physische Adresse des Ziel-Hosts",
    ],
    24: [
        "Der ARP-Cache wird geleert.",
        "Der aktuelle Inhalt des ARP-Cache wird angezeigt.",
        "Detaillierte Informationen des ARP-Cache werden angezeigt.",
        "Der ARP-Cache wird mit der Router-Schnittstelle synchronisiert.",
    ],
    25: [
        "Der Switch verwirft den Frame.",
        "Der Switch leitet den Frame nur an Port 2 weiter.",
        "Der Switch leitet den Frame an alle Ports außer Port 4 weiter.",
        "Der Switch leitet den Frame an alle Ports weiter.",
        "Der Switch leitet den Frame nur an Port 1 und 3 weiter.",
    ],
    26: [
        "Anycast",
        "Broadcast",
        "Echo Reply",
        "Echo Request",
        "Neighbor Solicitation",
        "Neighbor Advertisement",
    ],
    27: [
        "Das Netzwerk mit ARP-Antwort-Broadcasts fluten",
        "Switch-MAC-Tabellen mit falschen Adressen füllen",
        "IP-Adressen falschen MAC-Adressen zuordnen",
        "Netzwerk-Hosts mit ARP-Anfragen überlasten",
    ],
    28: [
        "die MAC-Adresse von S1",
        "die MAC-Adresse der G0/0-Schnittstelle auf R1",
        "die MAC-Adresse der G0/0-Schnittstelle auf R2",
        "die MAC-Adresse von S2",
        "die MAC-Adresse von File_server1",
    ],
    29: [
        "Neighbor-Tabelle",
        "ARP-Cache",
        "Routing-Tabelle",
        "MAC-Adresstabelle",
    ],
    30: [
        "Quell-MAC-Adresse",
        "Quell-IP-Adresse",
        "Ziel-MAC-Adresse",
        "Ethernet-Typ",
        "Ziel-IP-Adresse",
    ],
    31: [
        "Meldung nach Router-Zugriff anzeigen → Router(config)# banner motd #",
        "Sicherheit auf der Konsole bereitstellen → Router(config-line)# password class",
        "Namen auf dem Router konfigurieren → Router(config)# hostname CL1",
    ],
    32: [
        "Das Gerät neu starten.",
        "STRG-Z im Privileged-Modus eingeben.",
        "Den globalen Konfigurationsmodus verlassen.",
        "Das Gerät stromlos schalten.",
        "Privileged-EXEC-Modus verlassen und Enter drücken.",
    ],
    33: [
        "Remote-Zugriff mit Verschlüsselung → SSH",
        "Bevorzugte Out-of-Band-Zugriffsmethode → Konsole",
        "Remote-Zugriff per Einwahlverbindung → AUX",
        "Unsicherer Remote-Zugriff → Telnet",
    ],
    34: [
        "Phase 1 → POST ausführen und Bootstrap-Programm laden",
        "Phase 2 → Cisco-IOS-Software finden und laden",
        "Phase 3 → Startup-Konfigurationsdatei finden und laden",
    ],
    35: [
        "service password-encryption → R1(config)#",
        "enable → R1>",
        "copy running-config startup-config → R1#",
        "login → R1(config-line)#",
        "ip address 192.168.4.4 255.255.255.0 → R1(config-if)#",
    ],
    36: [
        "Routing-Tabelle speichern",
        "Inhalt bei Stromausfall behalten",
        "Startup-Konfigurationsdatei speichern",
        "Running-Konfigurationsdatei enthalten",
        "ARP-Tabelle speichern",
    ],
    37: [
        "Das IOS-Image ist beschädigt.",
        "Cisco IOS fehlt im Flash-Speicher.",
        "Die Konfigurationsdatei fehlt im NVRAM.",
        "Der POST-Prozess hat einen Hardwarefehler erkannt.",
    ],
    38: [
        "Der Switch erhält eine Management-Schnittstelle mit der Adresse 172.16.100.1.",
        "Der Switch kann von einem Host in einem anderen Netzwerk remote verwaltet werden.",
        "Der Switch kann mit anderen Hosts im Netz 172.16.100.0 kommunizieren.",
        "Der Switch darf Frames nur an das Gateway 172.16.100.1 senden und empfangen.",
    ],
    39: [
        "Der SSH-Client auf dem Switch wird aktiviert.",
        "Die Kommunikation zwischen Switch und Remote-Benutzern wird verschlüsselt.",
        "Der Switch verlangt Benutzername/Passwort für Remote-Zugriff.",
        "Der Switch verlangt Remote-Verbindungen über proprietäre Client-Software.",
    ],
    40: ["172.24.255.17", "172.24.1.22", "172.20.0.254", "172.24.255.4", "172.20.1.18"],
    41: [
        "R1> → enable",
        "R1# → copy running-config startup-config",
        "R1(config-line)# → login",
        "R1(config)# → interface fastethernet 0/0",
    ],
    42: [
        "interface fastethernet 0/0",
        "line vty 0 4",
        "line console 0",
        "enable secret cisco",
        "login",
        "password cisco",
    ],
    43: [
        "Es ist die IP-Adresse der Router1-Schnittstelle, die das Unternehmen mit dem Internet verbindet.",
        "Es ist die IP-Adresse der Router1-Schnittstelle, die das PC1-LAN mit Router1 verbindet.",
        "Es ist die IP-Adresse von Switch1, der PC1 mit anderen Geräten im LAN verbindet.",
        "Es ist die IP-Adresse des ISP-Netzwerkgeräts in der Cloud.",
    ],
    44: [
        "Paketweiterleitung",
        "Mikrosegmentierung",
        "Domänennamenauflösung",
        "Pfadauswahl",
        "Flusskontrolle",
    ],
    45: [
        "Der Inhalt des ROM ändert sich.",
        "Der Inhalt des RAM ändert sich.",
        "Der Inhalt des NVRAM ändert sich.",
        "Der Inhalt des Flash ändert sich.",
    ],
    46: [
        "Der Host kann nicht mit anderen Hosts im lokalen Netzwerk kommunizieren.",
        "Der Switch leitet vom Host initiierte Pakete nicht weiter.",
        "Der Host muss ARP nutzen, um die korrekte Standard-Gateway-Adresse zu ermitteln.",
        "Der Host kann nicht mit Hosts in anderen Netzwerken kommunizieren.",
        "Ein Ping vom Host zu 127.0.0.1 wäre nicht erfolgreich.",
    ],
    47: [
        "Manuelle statische ARP-Einträge könnten ARP-Poisoning oder MAC-Spoofing erleichtern.",
        "Auf großen Netzen mit geringer Bandbreite können viele ARP-Broadcasts Verzögerungen verursachen.",
        "Angreifer könnten IP-MAC-Zuordnungen in ARP-Nachrichten manipulieren, um Verkehr abzufangen.",
        "Viele ARP-Anfragen könnten die Host-MAC-Tabelle überlaufen und Kommunikation verhindern.",
        "Mehrere ARP-Antworten führen dazu, dass die Switch-MAC-Tabelle passende Einträge enthält.",
    ],
    48: [
        "R1: G0/0 und S0/0/0 / R2: G0/0 und S0/0/0",
        "R1: G0/1 und S0/0/1 / R2: G0/0 und S0/0/1",
        "R1: G0/0 und S0/0/0 / R2: G0/1 und S0/0/0",
        "R1: G0/0 und S0/0/1 / R2: G0/1 und S0/0/1",
    ],
    49: ["Protokoll", "Ziel-IPv4-Adresse", "Quell-IPv4-Adresse", "TTL"],
    50: ["Differentiated Services", "Ziel-IPv4-Adresse", "Quell-IPv4-Adresse", "Protokoll"],
    51: ["Quell-IPv4-Adresse", "Ziel-IPv4-Adresse", "Protokoll", "TTL"],
    52: ["Header-Prüfsumme", "Quell-IPv4-Adresse", "Protokoll", "TTL"],
    53: ["10.27.14.148", "10.27.14.1", "10.14.15.254", "203.0.113.39", "10.27.15.17"],
    54: ["Ziel-IPv4-Adresse", "Protokoll", "TTL", "Header-Prüfsumme"],
    55: ["TTL", "Quell-IPv4-Adresse", "Protokoll", "Header-Prüfsumme"],
    56: ["Version", "Quell-IPv4-Adresse", "Protokoll", "TTL"],
    57: ["Protokoll", "Version", "Differentiated Services", "Header-Prüfsumme"],
    58: ["Version", "Differentiated Services", "Header-Prüfsumme", "TTL"],
    59: [
        "Einträge in der ARP-Tabelle sind zeitgestempelt und werden nach Timeout gelöscht.",
        "Ein statischer IP-zu-MAC-Eintrag kann manuell in die ARP-Tabelle eingegeben werden.",
        "Das Typ-Feld 0x806 erscheint im Ethernet-Frame-Header.",
        "Die Port-zu-MAC-Tabelle eines Switches hat dieselben Einträge wie die ARP-Tabelle.",
    ],
    60: [
        "Ein statischer IP-zu-MAC-Eintrag kann manuell in die ARP-Tabelle eingegeben werden.",
        "Einträge in der ARP-Tabelle sind zeitgestempelt und werden nach Timeout gelöscht.",
        "Das Typ-Feld 0x806 erscheint im Ethernet-Frame-Header.",
        "Die Port-zu-MAC-Tabelle eines Switches hat dieselben Einträge wie die ARP-Tabelle.",
    ],
    61: [
        "Ein statischer IP-zu-MAC-Eintrag kann manuell in die ARP-Tabelle eingegeben werden.",
        "Die Ziel-MAC-Adresse FF-FF-FF-FF-FF-FF erscheint im Ethernet-Frame-Header.",
        "Die Quell-MAC-Adresse erscheint im Ethernet-Frame-Header.",
        "Die Port-zu-MAC-Tabelle eines Switches hat dieselben Einträge wie die ARP-Tabelle.",
    ],
    62: [
        "Lokale Hosts lernen die MAC-Adresse des Standard-Gateways.",
        "Die Ziel-MAC-Adresse FF-FF-FF-FF-FF-FF erscheint im Ethernet-Frame-Header.",
        "Die Quell-MAC-Adresse erscheint im Ethernet-Frame-Header.",
        "Die Port-zu-MAC-Tabelle eines Switches hat dieselben Einträge wie die ARP-Tabelle.",
    ],
    63: ["192.168.235.234", "192.168.235.1", "10.234.235.254", "203.0.113.3", "192.168.234.114"],
    64: [
        "Die Ziel-MAC-Adresse FF-FF-FF-FF-FF-FF erscheint im Ethernet-Frame-Header.",
        "Die Quell-MAC-Adresse erscheint im Ethernet-Frame-Header.",
        "Das Typ-Feld 0x806 erscheint im Ethernet-Frame-Header.",
        "ARP-Antworten werden als Broadcast gesendet, wenn ein Host eine ARP-Anfrage erhält.",
    ],
    65: [
        "Die Quell-MAC-Adresse erscheint im Ethernet-Frame-Header.",
        "Die Ziel-MAC-Adresse FF-FF-FF-FF-FF-FF erscheint im Ethernet-Frame-Header.",
        "Das Typ-Feld 0x806 erscheint im Ethernet-Frame-Header.",
        "ARP-Antworten werden als Broadcast gesendet, wenn ein Host eine ARP-Anfrage erhält.",
    ],
    66: [
        "Die Ziel-MAC-Adresse FF-FF-FF-FF-FF-FF erscheint im Ethernet-Frame-Header.",
        "Das Typ-Feld 0x806 erscheint im Ethernet-Frame-Header.",
        "Einträge in der ARP-Tabelle sind zeitgestempelt und werden nach Timeout gelöscht.",
        "ARP-Antworten werden als Broadcast gesendet, wenn ein Host eine ARP-Anfrage erhält.",
    ],
    67: [
        "Das Typ-Feld 0x806 erscheint im Ethernet-Frame-Header.",
        "Die Ziel-MAC-Adresse FF-FF-FF-FF-FF-FF erscheint im Ethernet-Frame-Header.",
        "Einträge in der ARP-Tabelle sind zeitgestempelt und werden nach Timeout gelöscht.",
        "ARP-Antworten werden als Broadcast gesendet, wenn ein Host eine ARP-Anfrage erhält.",
    ],
    68: [
        "Das Typ-Feld 0x806 erscheint im Ethernet-Frame-Header.",
        "Die Ziel-MAC-Adresse FF-FF-FF-FF-FF-FF erscheint im Ethernet-Frame-Header.",
        "Einträge in der ARP-Tabelle sind zeitgestempelt und werden nach Timeout gelöscht.",
        "Die Port-zu-MAC-Tabelle eines Switches hat dieselben Einträge wie die ARP-Tabelle.",
    ],
    69: ["172.29.157.156", "172.29.157.1", "10.156.157.254", "198.51.100.177", "172.29.156.36"],
    70: ["192.168.191.189", "192.168.191.1", "10.190.191.254", "198.51.100.213", "192.168.190.70"],
    71: ["192.168.225.223", "192.168.225.1", "10.224.225.254", "203.0.113.246", "192.168.224.103"],
    72: ["10.118.62.196", "10.118.62.1", "10.62.63.254", "209.165.200.87", "10.118.63.65"],
    73: ["172.19.98.230", "172.19.98.1", "10.98.99.254", "209.165.200.120", "172.19.99.99"],
    74: ["172.20.132.13", "172.20.132.1", "10.132.133.254", "198.51.100.156", "172.20.133.132"],
    75: ["192.168.167.166", "192.168.167.1", "10.166.167.254", "198.51.100.189", "192.168.166.46"],
    76: ["192.168.201.200", "192.168.201.1", "10.200.201.254", "203.0.113.222", "192.168.200.80"],
}
