"""German literal translations for all 76 question prompts."""

QUESTION_DE = {
    1: "Welche Informationen werden von Routern verwendet, um ein Datenpaket in Richtung seines Ziels weiterzuleiten?",
    2: "Ein Computer muss ein Paket an einen Ziel-Host im selben LAN senden. Wie wird das Paket gesendet?",
    3: "Ein Router empfängt ein Paket über die Gigabit-0/0-Schnittstelle und bestimmt, dass das Paket über die Gigabit-0/1-Schnittstelle weitergeleitet werden muss. Was wird der Router als Nächstes tun?",
    4: "Welche IPv4-Adresse kann ein Host verwenden, um die Loopback-Schnittstelle anzupingen?",
    5: "Ein Computer kann auf Geräte im selben Netzwerk zugreifen, aber nicht auf Geräte in anderen Netzwerken. Was ist die wahrscheinliche Ursache dieses Problems?",
    6: "Welche Aussage beschreibt ein Merkmal des IP-Protokolls?",
    7: "Warum wird NAT in IPv6 nicht benötigt?",
    8: "Welchen Parameter verwendet der Router, um den Pfad zum Ziel zu wählen, wenn mehrere Routen verfügbar sind?",
    9: "Welche zwei Dienste werden von der OSI-Netzwerkschicht bereitgestellt? (Wählen Sie zwei.)",
    10: "Was ist innerhalb eines Produktionsnetzwerks der Zweck, einen Switch mit einer Standard-Gateway-Adresse zu konfigurieren?",
    11: "Was ist ein grundlegendes Merkmal des IP-Protokolls?",
    12: "Welches Feld im IPv4-Header wird verwendet, um zu verhindern, dass ein Paket ein Netzwerk endlos durchläuft?",
    13: "Was ist ein Vorteil, den der vereinfachte IPv6-Header gegenüber IPv4 bietet?",
    14: "Welches IPv4-Headerfeld identifiziert das Protokoll der oberen Schicht, das im Paket transportiert wird?",
    15: "Beziehen Sie sich auf die Abbildung. Ordnen Sie die Pakete anhand ihrer Ziel-IP-Adresse den ausgehenden Schnittstellen am Router zu. (Nicht alle Ziele werden verwendet.)",
    16: "Welche Informationen liefert der Loopback-Test?",
    17: "Welcher Routing-Tabelleneintrag hat eine Next-Hop-Adresse, die einem Zielnetzwerk zugeordnet ist?",
    18: "Wie stellen Hosts sicher, dass ihre Pakete zum richtigen Netzwerkziel geleitet werden?",
    19: "Beim Transport von Daten aus Echtzeitanwendungen, wie Streaming-Audio und -Video: Welches Feld im IPv6-Header kann verwendet werden, um Router und Switches darüber zu informieren, für die Pakete derselben Konversation denselben Pfad beizubehalten?",
    20: "Welche Aussage beschreibt die Funktion des Address Resolution Protocol?",
    21: "Unter welchen zwei Umständen wird ein Switch einen Frame über jeden Port fluten, außer über den Port, an dem der Frame empfangen wurde? (Wählen Sie zwei.)",
    22: "Welche Aussage beschreibt die Behandlung von ARP-Anfragen auf der lokalen Verbindung?",
    23: "Welche Zieladresse wird in einem ARP-Request-Frame verwendet?",
    24: "Ein Netzwerktechniker führt auf einem PC den Befehl arp -d * aus, nachdem der mit dem LAN verbundene Router neu konfiguriert wurde. Was ist das Ergebnis, nachdem dieser Befehl ausgeführt wurde?",
    25: "Beziehen Sie sich auf die Abbildung. Die Abbildung zeigt ein kleines geswitchtes Netzwerk und den Inhalt der MAC-Adresstabelle des Switches. PC1 hat einen an PC3 adressierten Frame gesendet. Was wird der Switch mit dem Frame tun?",
    26: "Welche zwei Typen von IPv6-Nachrichten werden anstelle von ARP für die Adressauflösung verwendet?",
    27: "Was ist das Ziel eines ARP-Spoofing-Angriffs?",
    28: "Beziehen Sie sich auf die Abbildung. PC1 versucht, eine Verbindung zu File_server1 herzustellen, und sendet eine ARP-Anfrage, um eine Ziel-MAC-Adresse zu erhalten. Welche MAC-Adresse wird PC1 in der ARP-Antwort erhalten?",
    29: "Wo werden Zuordnungen von IPv4-Adressen zu Layer-2-Ethernet-Adressen auf einem Host-Computer gepflegt?",
    30: "Welche wichtige Information im Ethernet-Frame-Header wird von einem Layer-2-Gerät untersucht, um die Daten weiterzuleiten?",
    31: "Ordnen Sie die Befehle den richtigen Aktionen zu. (Nicht alle Optionen werden verwendet.)",
    32: "Ein neuer Netzwerkadministrator wurde gebeten, auf einem Cisco-Gerät eine Banner-Nachricht einzugeben. Wie kann ein Netzwerkadministrator am schnellsten testen, ob das Banner korrekt konfiguriert ist?",
    33: "Ein Netzwerkadministrator benötigt Zugriff, um Router und Switches lokal und remote zu verwalten. Ordnen Sie die Beschreibung der Zugriffsmethode zu. (Nicht alle Optionen werden verwendet.)",
    34: "Ordnen Sie die Phasen den Funktionen während des Bootvorgangs eines Cisco-Routers zu. (Nicht alle Optionen werden verwendet.)",
    35: "Ordnen Sie den Befehl dem Gerätemodus zu, in dem der Befehl eingegeben wird. (Nicht alle Optionen werden verwendet.)",
    36: "Welche zwei Funktionen hat NVRAM? (Wählen Sie zwei.)",
    37: "Ein Router startet und wechselt in den Setup-Modus. Was ist der Grund dafür?",
    38: "Der globale Konfigurationsbefehl ip default-gateway 172.16.100.1 wird auf einen Switch angewendet. Welche Auswirkung hat dieser Befehl?",
    39: "Was passiert, wenn der Befehl transport input ssh auf den vty-Leitungen des Switches eingegeben wird?",
    40: "Beziehen Sie sich auf die Abbildung. Ein Benutzer-PC hat erfolgreich Pakete zu www.cisco.com übertragen. Welche IP-Adresse verwendet der Benutzer-PC als Ziel, um seine Daten aus dem lokalen Netzwerk weiterzuleiten?",
    41: "Ordnen Sie den Konfigurationsmodus dem Befehl zu, der in diesem Modus verfügbar ist. (Nicht alle Optionen werden verwendet.)",
    42: "Welche drei Befehle werden verwendet, um einen sicheren Zugriff auf einen Router über eine Verbindung zur Konsolenschnittstelle einzurichten? (Wählen Sie drei.)",
    43: "Beziehen Sie sich auf die Abbildung. Betrachten Sie die gezeigte IP-Adresskonfiguration von PC1. Was beschreibt die Standard-Gateway-Adresse?",
    44: "Welche zwei Funktionen sind primäre Funktionen eines Routers? (Wählen Sie zwei.)",
    45: "Welche Auswirkung hat die Verwendung des Befehls Router# copy running-config startup-config auf einem Router?",
    46: "Was passiert, wenn die Standard-Gateway-Adresse auf einem Host falsch konfiguriert ist?",
    47: "Welche zwei potenziellen Netzwerkprobleme können sich aus dem ARP-Betrieb ergeben? (Wählen Sie zwei.)",
    48: "Öffnen Sie die PT-Aktivität. Führen Sie die Aufgaben in den Aktivitätsanweisungen aus und beantworten Sie anschließend die Frage. Welche Schnittstellen in jedem Router sind aktiv und betriebsbereit?",
    49: "Welcher Begriff beschreibt ein Feld im IPv4-Paketheader, das verwendet wird, um das Protokoll der nächsten Ebene zu identifizieren?",
    50: "Welcher Begriff beschreibt ein Feld im IPv4-Paketheader, das einen 8-Bit-Binärwert enthält, der verwendet wird, um die Priorität jedes Pakets zu bestimmen?",
    51: "Welcher Begriff beschreibt ein Feld im IPv4-Paketheader, das einen 32-Bit-Binärwert enthält, der einer Schnittstelle auf dem sendenden Gerät zugeordnet ist?",
    52: "Welcher Begriff beschreibt ein Feld im IPv4-Paketheader, das verwendet wird, um Beschädigungen im IPv4-Header zu erkennen?",
    53: "Beziehen Sie sich auf die Abbildung. Ein Netzwerkadministrator verbindet einen neuen Host mit dem Payroll LAN. Der Host muss mit entfernten Netzwerken kommunizieren. Welche IP-Adresse würde auf dem neuen Host als Standard-Gateway konfiguriert?",
    54: "Welcher Begriff beschreibt ein Feld im IPv4-Paketheader, das eine Unicast-, Multicast- oder Broadcast-Adresse enthält?",
    55: "Welcher Begriff beschreibt ein Feld im IPv4-Paketheader, das verwendet wird, um die Lebensdauer eines Pakets zu begrenzen?",
    56: "Welcher Begriff beschreibt ein Feld im IPv4-Paketheader, das einen 4-Bit-Binärwert enthält, der auf 0100 gesetzt ist?",
    57: "Welcher Begriff beschreibt ein Feld im IPv4-Paketheader, das verwendet wird, um das Protokoll der nächsten Ebene zu identifizieren?",
    58: "Welcher Begriff beschreibt ein Feld im IPv4-Paketheader, das einen 4-Bit-Binärwert enthält, der auf 0100 gesetzt ist?",
    59: "Welche Eigenschaft von ARP bewirkt, dass zwischengespeicherte IP-zu-MAC-Zuordnungen länger im Speicher bleiben?",
    60: "Welche Eigenschaft von ARP ermöglicht es, MAC-Adressen häufig verwendeter Server in der ARP-Tabelle fest zu hinterlegen?",
    61: "Welche Eigenschaft von ARP ermöglicht es, MAC-Adressen häufig verwendeter Server in der ARP-Tabelle fest zu hinterlegen?",
    62: "Welche Eigenschaft von ARP ermöglicht es Hosts in einem LAN, Verkehr zu entfernten Netzwerken zu senden?",
    63: "Beziehen Sie sich auf die Abbildung. Ein Netzwerkadministrator verbindet einen neuen Host mit dem Registrar LAN. Der Host muss mit entfernten Netzwerken kommunizieren. Welche IP-Adresse würde auf dem neuen Host als Standard-Gateway konfiguriert?",
    64: "Welche Eigenschaft von ARP zwingt alle Ethernet-NICs, eine ARP-Anfrage zu verarbeiten?",
    65: "Welche Eigenschaft von ARP bewirkt, dass eine Antwort nur an die Quelle gesendet wird, die eine ARP-Anfrage gesendet hat?",
    66: "Welche Eigenschaft von ARP bewirkt, dass die Anfrage über alle Ports eines Switches geflutet wird, außer über den Port, der die ARP-Anfrage empfängt?",
    67: "Welche Eigenschaft von ARP bewirkt, dass NICs, die eine ARP-Anfrage empfangen, den Datenteil des Ethernet-Frames an den ARP-Prozess weitergeben?",
    68: "Welche Eigenschaft von ARP bewirkt, dass NICs, die eine ARP-Anfrage empfangen, den Datenteil des Ethernet-Frames an den ARP-Prozess weitergeben?",
    69: "Beziehen Sie sich auf die Abbildung. Ein Netzwerkadministrator verbindet einen neuen Host mit dem Service LAN. Der Host muss mit entfernten Netzwerken kommunizieren. Welche IP-Adresse würde auf dem neuen Host als Standard-Gateway konfiguriert?",
    70: "Beziehen Sie sich auf die Abbildung. Ein Netzwerkadministrator verbindet einen neuen Host mit dem Medical LAN. Der Host muss mit entfernten Netzwerken kommunizieren. Welche IP-Adresse würde auf dem neuen Host als Standard-Gateway konfiguriert?",
    71: "Beziehen Sie sich auf die Abbildung. Ein Netzwerkadministrator verbindet einen neuen Host mit dem Registrar LAN. Der Host muss mit entfernten Netzwerken kommunizieren. Welche IP-Adresse würde auf dem neuen Host als Standard-Gateway konfiguriert?",
    72: "Beziehen Sie sich auf die Abbildung. Ein Netzwerkadministrator verbindet einen neuen Host mit dem Manager LAN. Der Host muss mit entfernten Netzwerken kommunizieren. Welche IP-Adresse würde auf dem neuen Host als Standard-Gateway konfiguriert?",
    73: "Beziehen Sie sich auf die Abbildung. Ein Netzwerkadministrator verbindet einen neuen Host mit dem Store LAN. Der Host muss mit entfernten Netzwerken kommunizieren. Welche IP-Adresse würde auf dem neuen Host als Standard-Gateway konfiguriert?",
    74: "Beziehen Sie sich auf die Abbildung. Ein Netzwerkadministrator verbindet einen neuen Host mit dem Store LAN. Der Host muss mit entfernten Netzwerken kommunizieren. Welche IP-Adresse würde auf dem neuen Host als Standard-Gateway konfiguriert?",
    75: "Beziehen Sie sich auf die Abbildung. Ein Netzwerkadministrator verbindet einen neuen Host mit dem Service LAN. Der Host muss mit entfernten Netzwerken kommunizieren. Welche IP-Adresse würde auf dem neuen Host als Standard-Gateway konfiguriert?",
    76: "Beziehen Sie sich auf die Abbildung. Ein Netzwerkadministrator verbindet einen neuen Host mit dem Medical LAN. Der Host muss mit entfernten Netzwerken kommunizieren. Welche IP-Adresse würde auf dem neuen Host als Standard-Gateway konfiguriert?",
}
